export function renderStudioClientJs(): string {
  return `(()=>{
const $=(selector)=>document.querySelector(selector);let linkPoll;let activeApproval;let activeReel;let sessionAuthenticated=false;
const selected=(name)=>document.querySelector('input[name="'+name+'"]:checked')?.value;
const api=(url,options={})=>fetch(url,options);
function setVisibility(){const intent=selected('intent');$('#siteDetails').classList.toggle('hidden',intent==='reels');$('#reelStyles').classList.toggle('hidden',intent==='website')}
function showWorkspace(){$('#modeChooser').classList.add('hidden');$('#path').classList.add('hidden');$('#linkPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');setVisibility()}
function showOutcome(mode){$('#modeChooser').classList.add('hidden');$('#path').classList.remove('hidden');if(mode==='both'){document.querySelector('input[name="intent"][value="both"]').checked=true}setVisibility();$('#path').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('input[name="intent"]').forEach((item)=>item.addEventListener('change',setVisibility));setVisibility();
$('#studioModeButton').addEventListener('click',()=>showOutcome('studio'));$('#bothModeButton').addEventListener('click',()=>showOutcome('both'));
api('/api/studio/me',{cache:'no-store'}).then((response)=>{if(response.ok){sessionAuthenticated=true;$('#linkButton').textContent='Open the optional Visual Studio'}}).catch(()=>{});
$('#linkButton').addEventListener('click',async()=>{if(sessionAuthenticated){showWorkspace();return}const response=await api('/api/studio/link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent:selected('intent')})});if(!response.ok){$('#linkButton').textContent=response.status===429?'Try again in a few minutes.':'Could not start sign-in. Try again.';return}const result=await response.json();$('#path').classList.add('hidden');$('#linkPanel').classList.remove('hidden');$('#whatsappLink').href=result.whatsappUrl;linkPoll=setInterval(checkLink,1800)});
async function checkLink(){const response=await api('/api/studio/link/status',{method:'POST',cache:'no-store'});if(response.status===202)return;if(!response.ok){clearInterval(linkPoll);$('#linkStatus').textContent='This link expired. Refresh to start again.';return}clearInterval(linkPoll);showWorkspace()}
function offerings(form){const result=[];for(let index=1;index<=3;index++){const name=form['offeringName'+index].value.trim();if(!name)continue;const raw=form['offeringPrice'+index].value;result.push({name,description:form['offeringDescription'+index].value.trim(),currency:form['offeringCurrency'+index].value,...(raw!==''?{priceMinor:Math.round(Number(raw)*100)}:{})})}return result}
function friendlyMissing(missing){const labels={orderWhatsAppNumber:'order WhatsApp number',fulfillmentArea:'area served',leadTime:'lead time',offerings:'at least one product or service',referenceAssetIds:'at least one real photo'};return missing.map((item)=>labels[item]||item).join(', ')}
function showApproval(result,kind){activeApproval=result.approval.approvalId;activeReel=kind==='reel'?result.reelId:undefined;$('#checklist').textContent=result.approval.checklist;$('#previewLink').classList.toggle('hidden',kind==='reel');$('#publishPanel').querySelector('h3').textContent=kind==='reel'?'Your reel plan is ready':'Your private preview passed its checks';$('#publishButton').textContent=kind==='reel'?'Approve private render':'Publish this version';$('#confirmPublish').parentElement.lastChild.textContent=kind==='reel'?' I reviewed this exact plan and approve one private render.':' I reviewed this exact preview and want it live.';$('#publishPanel').classList.remove('hidden');$('#publishPanel').scrollIntoView({behavior:'smooth'})}
$('#projectForm').addEventListener('submit',async(event)=>{event.preventDefault();const form=event.target;const status=$('#saveStatus');const submit=form.querySelector('button[type="submit"]');submit.disabled=true;status.textContent='Saving your details and media securely…';$('#publishPanel').classList.add('hidden');const intent=selected('intent');const payload={intent,businessName:form.businessName.value,description:form.description.value,referenceAssetIds:[],siteAssetIds:[],suppliedClaims:form.suppliedClaims.value.split(/\\r?\\n/).map((value)=>value.trim()).filter(Boolean)};if(intent!=='reels'){payload.siteStyle=selected('siteStyle');payload.orderWhatsAppNumber=form.orderWhatsAppNumber.value;payload.fulfillmentArea=form.fulfillmentArea.value;payload.leadTime=form.leadTime.value;payload.timezone=form.timezone.value;payload.offerings=offerings(form)}if(intent!=='website'){payload.reelTemplate=selected('reelTemplate');payload.layerOverrides={hook:form.hook.value,proof:form.proof.value,cta:form.cta.value,accent:form.accent.value,pacing:form.pacing.value}}
let saved=await api('/api/studio/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!saved.ok){status.textContent='Check the business details and try again.';submit.disabled=false;return}let project=await saved.json();const files=Array.from($('#references').files||[]);const assetIds=[];const siteAssetIds=[];for(let index=0;index<files.length;index++){const file=files[index];const localId='reference-'+project.projectId.slice(-12)+'-'+(index+1);const upload=await api('/api/studio/assets/'+localId,{method:'PUT',headers:{'content-type':file.type,'x-axcas-project-id':project.projectId},body:file});if(!upload.ok){status.textContent='One file could not upload. Use JPG, PNG, WebP or MP4 under 16 MB.';submit.disabled=false;return}const uploaded=await upload.json();assetIds.push(uploaded.assetId);if(file.type.startsWith('image/'))siteAssetIds.push(uploaded.assetId)}
if(assetIds.length){const revision={...payload,projectId:project.projectId,parentRevisionId:project.revisionId,referenceAssetIds:assetIds,siteAssetIds};saved=await api('/api/studio/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(revision)});if(!saved.ok){status.textContent='Files uploaded, but the final draft could not be saved.';submit.disabled=false;return}project=await saved.json()}
if(intent==='reels'){status.textContent='Preparing your three angles and exact render checklist…';const response=await api('/api/studio/projects/'+project.projectId+'/reel',{method:'POST'});const result=await response.json().catch(()=>({}));if(!response.ok){status.textContent=result.stage==='needs_input'?'Add '+friendlyMissing(result.missing)+'.':'The reel plan needs a quick correction.';submit.disabled=false;return}status.textContent='Recommended angles: '+result.suggestions.join(' · ');showApproval(result,'reel');submit.disabled=false;return}
status.textContent='Building and independently checking your private preview…';const response=await api('/api/studio/projects/'+project.projectId+'/build',{method:'POST'});const result=await response.json().catch(()=>({}));if(response.status===409&&result.stage==='needs_input'){status.textContent='One quick correction: add '+friendlyMissing(result.missing)+'.';submit.disabled=false;return}if(!response.ok&&response.status!==202){status.textContent='The preview did not pass its checks yet. Nothing was published.';submit.disabled=false;return}$('#previewLink').href=result.previewUrl;status.textContent=response.status===202?'Private preview ready; independent verification is queued.':'Private preview ready and checked.';if(result.stage==='approval_required')showApproval(result,'site');submit.disabled=false});
async function pollReel(reelId){const response=await api('/api/studio/reels/'+reelId,{cache:'no-store'});if(!response.ok){$('#publishStatus').textContent='Render status is temporarily unavailable.';return}const result=await response.json();if(result.status==='rendered'){const link=document.createElement('a');link.href=result.mediaUrl;link.textContent='Download your finished reel';$('#publishStatus').textContent='Render complete. ';$('#publishStatus').appendChild(link);return}if(result.status==='failed'){$('#publishStatus').textContent='The render failed safely; no file was delivered.';return}$('#publishStatus').textContent='Rendering privately on Axcas…';setTimeout(()=>pollReel(reelId),4000)}
$('#publishButton').addEventListener('click',async()=>{const status=$('#publishStatus');if(!$('#confirmPublish').checked){status.textContent='Tick the review box before continuing.';return}if(!activeApproval)return;$('#publishButton').disabled=true;status.textContent=activeReel?'Starting one private render…':'Publishing this exact checked version…';const response=await api('/api/studio/approvals/'+activeApproval,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision:'approved'})});const result=await response.json().catch(()=>({}));if(!response.ok){status.textContent='Could not complete the approval. Refresh and try again.';$('#publishButton').disabled=false;return}if(result.stage==='rendering'&&result.reelId){pollReel(result.reelId);return}if(result.siteUrl){status.textContent='Live now: ';const link=document.createElement('a');link.href=result.siteUrl;link.textContent=result.siteUrl;link.target='_blank';link.rel='noopener noreferrer';status.appendChild(link)}else status.textContent='Approved. Publication is finishing now.'});
})();`;
}
