import { REEL_FORMATS } from "../../domain/src/studio";

export function renderStudio(): string {
  const reelCards = REEL_FORMATS.map((format, index) => `<label class="choice compact"><input type="radio" name="reelTemplate" value="${format.id}"${index === 0 ? " checked" : ""}><span><strong>${format.name}</strong><small>${format.bestFor}</small></span></label>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Build a complete small-business website and original reels with Axcas."><title>Axcas Studio — websites and reels</title><link rel="stylesheet" href="/studio.css"></head>
  <body data-pg="studio"><header><a href="/" class="brand">Axcas</a><span class="status">Studio beta</span></header><main>
    <section class="intro"><p class="eyebrow">Start with one outcome</p><h1>What do you want Axcas to make?</h1><p>A guided workspace when you want more control. WhatsApp remains the fastest option.</p></section>
    <section id="path" class="panel"><div class="grid three">
      <label class="choice"><input type="radio" name="intent" value="website" checked><span><b>01</b><strong>Build a website</strong><small>Choose a complete style, add your business and preview before publishing.</small></span></label>
      <label class="choice"><input type="radio" name="intent" value="reels"><span><b>02</b><strong>Create reels</strong><small>Upload references and use editable human-led motion formats.</small></span></label>
      <label class="choice"><input type="radio" name="intent" value="both"><span><b>03</b><strong>I need both</strong><small>One brand workspace for the website, reel library and feedback loop.</small></span></label>
    </div><button id="linkButton" class="primary">Continue with WhatsApp</button><p class="fine">You verify ownership by sending one prefilled WhatsApp message. Axcas hosts the workspace and media.</p></section>
    <section id="linkPanel" class="panel hidden"><p class="eyebrow">Secure sign-in</p><h2>Link this browser to your WhatsApp</h2><p>Open the prefilled message and send it unchanged. This page will unlock automatically.</p><a id="whatsappLink" class="primary" rel="noopener noreferrer">Open WhatsApp</a><p id="linkStatus" class="fine">Waiting for the message…</p></section>
    <section id="workspace" class="panel hidden"><div class="split"><div><p class="eyebrow">Your workspace</p><h2>Create a structured draft</h2></div><div class="account">WhatsApp verified</div></div>
      <form id="projectForm"><label>Business name<input name="businessName" maxlength="100" required placeholder="Maya Studio"></label><label>Describe the business and goal<textarea name="description" maxlength="500" required placeholder="What you sell, where you operate, and what this project should achieve"></textarea></label>
      <fieldset id="siteStyles"><legend>Website style</legend><div class="grid five">${["minimal","editorial","catalog","services","portfolio"].map((style, index) => `<label class="choice compact"><input type="radio" name="siteStyle" value="${style}"${index === 0 ? " checked" : ""}><span><strong>${style[0].toUpperCase() + style.slice(1)}</strong></span></label>`).join("")}</div></fieldset>
      <fieldset id="reelStyles"><legend>Reel format</legend><div class="grid templates">${reelCards}</div><p class="fine">Formats use your real footage, photos, reviews and ideas. Axcas does not make “AI-looking” product content.</p><div class="layer-grid"><label>Hook layer<input name="hook" maxlength="120" value="Wait—look at this"></label><label>Proof layer<input name="proof" maxlength="120" value="Real work. Real result."></label><label>CTA layer<input name="cta" maxlength="120" value="Message us to know more"></label><label>Accent colour<input name="accent" type="color" value="#fe5b3a"></label><label>Pacing<select name="pacing"><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="calm">Calm</option></select></label></div></fieldset>
      <label>Reference photos or videos<input id="references" type="file" accept="image/jpeg,image/png,image/webp,video/mp4" multiple></label><button class="primary" type="submit">Save project</button><p id="saveStatus" class="fine"></p></form>
    </section>
  </main><footer>Axcas provides the workspace, storage, rendering and hosting. You provide the business truth and content rights.</footer><script src="/studio.js" defer></script></body></html>`;
}

export function renderStudioCss(): string {
  return `:root{--ink:#171717;--muted:#696969;--paper:#f4f1eb;--card:#fff;--line:#d9d3c9;--accent:#fe5b3a}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.5 Inter,ui-sans-serif,system-ui,sans-serif}header,main,footer{width:min(1180px,calc(100% - 32px));margin:auto}header{display:flex;justify-content:space-between;align-items:center;padding:24px 0}.brand{color:inherit;text-decoration:none;font-size:1.3rem;font-weight:900;letter-spacing:-.05em}.status,.account{border:1px solid var(--line);border-radius:999px;padding:6px 11px;background:#fff;font-size:.78rem;font-weight:750}.intro{padding:72px 0 34px}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-weight:850;font-size:.74rem;color:var(--accent)}h1{font-size:clamp(2.8rem,7vw,6.5rem);letter-spacing:-.075em;line-height:.92;margin:.2em 0}h2{font-size:clamp(2rem,4vw,3.4rem);letter-spacing:-.055em;line-height:1;margin:.2em 0}.intro>p:last-child{color:var(--muted);font-size:1.1rem}.panel{background:var(--card);border:1px solid var(--line);border-radius:24px;padding:28px;margin-bottom:22px}.grid,.layer-grid{display:grid;gap:12px}.three{grid-template-columns:repeat(3,1fr)}.five{grid-template-columns:repeat(5,1fr)}.templates{grid-template-columns:repeat(3,1fr)}.layer-grid{grid-template-columns:repeat(5,1fr);margin-top:18px;padding:18px;border:1px solid var(--line);border-radius:16px;background:#fbfaf7}.choice{display:block;cursor:pointer}.choice input{position:absolute;opacity:0}.choice span{display:flex;flex-direction:column;gap:10px;border:1px solid var(--line);border-radius:18px;padding:20px;min-height:190px;background:#fbfaf7}.choice input:checked+span{border:2px solid var(--ink);padding:19px;box-shadow:inset 0 0 0 4px #fff, inset 0 0 0 5px var(--accent)}.choice b{color:var(--accent);font-size:.75rem}.choice strong{font-size:1.12rem}.choice small,.fine{color:var(--muted)}.compact span{min-height:92px;padding:14px}.compact input:checked+span{padding:13px}.primary{display:inline-block;margin-top:20px;border:0;border-radius:12px;background:var(--ink);color:#fff;text-decoration:none;padding:13px 18px;font-weight:850;cursor:pointer}.hidden{display:none}.split{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}form{display:grid;gap:20px;margin-top:28px}label,legend{font-weight:750}input,textarea,select{display:block;width:100%;margin-top:8px;border:1px solid var(--line);border-radius:12px;background:#fff;padding:12px;font:inherit}input[type=color]{padding:4px;height:46px}textarea{min-height:120px;resize:vertical}fieldset{border:0;padding:0;margin:0}footer{padding:34px 0 60px;color:var(--muted);font-size:.85rem}@media(max-width:850px){.three,.templates,.layer-grid{grid-template-columns:1fr}.five{grid-template-columns:repeat(2,1fr)}.choice span{min-height:0}.intro{padding-top:38px}.split{display:block}.account{display:inline-block;margin-top:10px}}`;
}

export function renderStudioJs(): string {
  return `(()=>{const $=(s)=>document.querySelector(s);let poll;const selected=(n)=>document.querySelector('input[name="'+n+'"]:checked')?.value;function setVisibility(){const intent=selected('intent');$('#siteStyles').classList.toggle('hidden',intent==='reels');$('#reelStyles').classList.toggle('hidden',intent==='website')}document.querySelectorAll('input[name="intent"]').forEach((el)=>el.addEventListener('change',setVisibility));setVisibility();$('#linkButton').addEventListener('click',async()=>{const res=await fetch('/api/studio/link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent:selected('intent')})});if(!res.ok){$('#linkButton').textContent='Could not start sign-in. Try again.';return}const data=await res.json();$('#path').classList.add('hidden');$('#linkPanel').classList.remove('hidden');$('#whatsappLink').href=data.whatsappUrl;poll=setInterval(checkLink,1800)});async function checkLink(){const res=await fetch('/api/studio/link/status',{method:'POST',cache:'no-store'});if(res.status===202)return;if(!res.ok){clearInterval(poll);$('#linkStatus').textContent='This link expired. Refresh to start again.';return}clearInterval(poll);$('#linkPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');setVisibility()}$('#projectForm').addEventListener('submit',async(e)=>{e.preventDefault();const status=$('#saveStatus');status.textContent='Saving securely…';const intent=selected('intent');const payload={intent,businessName:e.target.businessName.value,description:e.target.description.value,referenceAssetIds:[]};if(intent!=='reels')payload.siteStyle=selected('siteStyle');if(intent!=='website'){payload.reelTemplate=selected('reelTemplate');payload.layerOverrides={hook:e.target.hook.value,proof:e.target.proof.value,cta:e.target.cta.value,accent:e.target.accent.value,pacing:e.target.pacing.value}}const created=await fetch('/api/studio/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!created.ok){status.textContent='Could not save this project. Check the fields and try again.';return}const project=await created.json();const files=Array.from($('#references').files||[]);for(let i=0;i<files.length;i++){const file=files[i];const id='reference-'+project.projectId.slice(-12)+'-'+(i+1);const upload=await fetch('/api/studio/assets/'+id,{method:'PUT',headers:{'content-type':file.type,'x-axcas-project-id':project.projectId},body:file});if(!upload.ok){status.textContent='Project saved, but one reference could not upload.';return}}status.textContent='Saved. Axcas has your brief'+(files.length?' and '+files.length+' reference file'+(files.length===1?'':'s'):'')+'. Your checked preview will use one approval checklist.'})})();`;
}
