export function renderStudioClientJs(): string {
  return `(()=>{
const $=(selector)=>document.querySelector(selector);const $$=(selector)=>Array.from(document.querySelectorAll(selector));const form=$('#projectForm');const previewDevice=$('[data-pg="preview-device"]');let linkPoll;let accountPoll;let activeApproval;let activeReel;let sessionAuthenticated=false;let formDirty=false;let loadedProjectId;let loadedRevision;let syncCursor;let projectCache=[];let conflictDraft;let conflictHead;let history=[];let mediaFiles=[];let mediaObjectUrls=[];
const selected=(name)=>document.querySelector('input[name="'+name+'"]:checked')?.value;
const api=(url,options={})=>fetch(url,options);
const node=(tag,className,text)=>{const item=document.createElement(tag);if(className)item.className=className;if(text!==undefined)item.textContent=text;return item};
const control=(name)=>form.elements.namedItem(name);
function setVersionCue(text){$('#versionCue').textContent=text}
function activateSection(name){$$('[data-editor-section]').forEach((section)=>section.classList.toggle('active',section.dataset.editorSection===name));$$('[data-editor-target]').forEach((button)=>button.classList.toggle('active',button.dataset.editorTarget===name));const active=$('[data-editor-section="'+name+'"]');if(active)active.scrollIntoView({behavior:'smooth',block:'nearest'})}
function setVisibility(){const intent=selected('intent');$('#siteDetails').classList.toggle('hidden',intent==='reels');$('#reelStyles').classList.toggle('hidden',intent==='website');$$('[data-editor-target="style"],[data-editor-target="offerings"],[data-editor-target="details"],[data-editor-target="trust"]').forEach((item)=>item.classList.toggle('hidden',intent==='reels'));$('.reel-nav').classList.toggle('hidden',intent==='website');const firstOffering=$('[data-offering] [data-field="name"]');if(firstOffering)firstOffering.required=intent!=='reels';renderCanvas()}
function showWorkspace(){$('#modeChooser').classList.add('hidden');$('#path').classList.add('hidden');$('#linkPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');setVisibility();renderCanvas();if(!accountPoll)accountPoll=setInterval(refreshChanges,5000)}
function showOutcome(mode){$('#modeChooser').classList.add('hidden');$('#path').classList.remove('hidden');if(mode==='both')document.querySelector('input[name="intent"][value="both"]').checked=true;setVisibility();$('#path').scrollIntoView({behavior:'smooth'})}
function setRadio(name,value){const input=document.querySelector('input[name="'+name+'"][value="'+value+'"]');if(input)input.checked=true}
function setField(name,value){const input=control(name);if(input)input.value=value??''}

function offeringValues(card){const value=(field)=>card.querySelector('[data-field="'+field+'"]')?.value||'';return{name:value('name'),description:value('description'),price:value('price'),currency:value('currency')||'INR'}}
function normalizeOfferings(){const cards=$$('[data-offering]');cards.forEach((card,index)=>{card.dataset.offering=String(index);card.querySelector('.offering-title').textContent='Offering '+(index+1);const name=card.querySelector('[data-field="name"]');name.required=index===0;card.querySelector('[data-move="up"]').disabled=index===0;card.querySelector('[data-move="down"]').disabled=index===cards.length-1});$('#addOfferingButton').disabled=cards.length>=8}
function makeField(labelText,field,type='text'){const label=node('label','',labelText);const input=document.createElement('input');input.dataset.field=field;input.type=type;if(field==='name')input.maxLength=120;if(field==='description')input.maxLength=240;if(field==='price'){input.min='0';input.step='0.01';input.placeholder='1500'}label.appendChild(input);return label}
function createOffering(values={},record=true){if($$('[data-offering]').length>=8)return;if(record)takeSnapshot();const card=node('article','offering');card.dataset.offering='';const head=node('div','offering-head');const title=node('strong','offering-title');const actions=node('div','offering-actions');for(const action of [['up','↑','Move up'],['down','↓','Move down'],['remove','×','Remove']]){const button=node('button','',action[1]);button.type='button';button.dataset.move=action[0];button.setAttribute('aria-label',action[2]+' offering');actions.appendChild(button)}head.append(title,actions);const fields=node('div','offering-fields');const name=makeField('Name','name');const description=makeField('Description','description');const price=makeField('Price','price','number');const currencyLabel=node('label','','Currency');const currency=document.createElement('select');currency.dataset.field='currency';for(const code of ['INR','USD']){const option=node('option','',code);option.value=code;currency.appendChild(option)}currencyLabel.appendChild(currency);fields.append(name,description,price,currencyLabel);card.append(head,fields);$('#offeringList').appendChild(card);for(const [key,value] of Object.entries(values)){const input=card.querySelector('[data-field="'+key+'"]');if(input)input.value=value??''}card.querySelector('[data-move="up"]').addEventListener('click',()=>moveOffering(card,-1));card.querySelector('[data-move="down"]').addEventListener('click',()=>moveOffering(card,1));card.querySelector('[data-move="remove"]').addEventListener('click',()=>removeOffering(card));normalizeOfferings();renderCanvas();return card}
function moveOffering(card,direction){const cards=$$('[data-offering]');const index=cards.indexOf(card);const target=cards[index+direction];if(!target)return;takeSnapshot();if(direction<0)target.before(card);else target.after(card);normalizeOfferings();markDirty()}
function removeOffering(card){takeSnapshot();const cards=$$('[data-offering]');if(cards.length===1){card.querySelectorAll('input').forEach((input)=>input.value='')}else card.remove();normalizeOfferings();markDirty()}
function hydrateOfferings(items){$('#offeringList').replaceChildren();for(const item of items?.length?items:[{}])createOffering({name:item.name||'',description:item.description||'',price:item.priceMinor===undefined?'':String(item.priceMinor/100),currency:item.currency||'INR'},false);normalizeOfferings()}
function offerings(){return $$('[data-offering]').map(offeringValues).filter((item)=>item.name.trim()).map((item)=>({name:item.name.trim(),description:item.description.trim(),currency:item.currency,...(item.price!==''?{priceMinor:Math.round(Number(item.price)*100)}:{})}))}

function draftSnapshot(){const names=['businessName','description','orderWhatsAppNumber','fulfillmentArea','leadTime','timezone','suppliedClaims','hook','proof','cta','accent','pacing'];const fields={};for(const name of names)fields[name]=control(name)?.value??'';return{fields,intent:selected('intent'),siteStyle:selected('siteStyle'),reelTemplate:selected('reelTemplate'),offerings:$$('[data-offering]').map(offeringValues)}}
function takeSnapshot(){const snapshot=JSON.stringify(draftSnapshot());if(history[history.length-1]!==snapshot){history.push(snapshot);if(history.length>30)history.shift();$('#undoButton').disabled=false}}
function restoreSnapshot(snapshot){const state=JSON.parse(snapshot);for(const [name,value] of Object.entries(state.fields||{}))setField(name,value);setRadio('intent',state.intent);setRadio('siteStyle',state.siteStyle);setRadio('reelTemplate',state.reelTemplate);hydrateOfferings(state.offerings);setVisibility();renderCanvas()}
function undoDraft(){const snapshot=history.pop();if(!snapshot)return;restoreSnapshot(snapshot);formDirty=true;setVersionCue('Unsaved changes');$('#undoButton').disabled=history.length===0}
function markDirty(){formDirty=true;setVersionCue('Unsaved changes');renderCanvas()}
function showConflict(result){conflictDraft=JSON.stringify(draftSnapshot());conflictHead=result.currentHeadRevisionId;$('#conflictPanel').classList.remove('hidden');$('#syncStatus').lastChild.textContent=' WhatsApp has a newer version. Your local edits are safe.';setVersionCue('Choose how to merge')}
async function resolveConflict(reapply){$('#conflictPanel').classList.add('hidden');formDirty=false;loadedRevision=undefined;await refreshAccount();if(reapply&&conflictDraft){restoreSnapshot(conflictDraft);if(conflictHead){form.dataset.revisionId=conflictHead;loadedRevision=conflictHead}formDirty=true;setVersionCue('Edits reapplied · not saved');$('#saveStatus').textContent='Your edits are now on top of the latest WhatsApp version. Review, then build again.'}conflictDraft=undefined;conflictHead=undefined}

function formatPrice(item){if(item.price==='')return'Contact for price';const amount=Number(item.price);if(!Number.isFinite(amount))return'Contact for price';return(item.currency==='USD'?'$':'₹')+amount.toLocaleString('en-IN')}
function renderCanvas(){const business=(control('businessName')?.value||'').trim()||'Your business name';const description=(control('description')?.value||'').trim()||'Describe what makes your business useful and different.';$('#canvasBusiness').textContent=business;$('#canvasEyebrow').textContent=business.toUpperCase();$('#canvasDescription').textContent=description;$('#canvasArea').textContent=(control('fulfillmentArea')?.value||'').trim()||'Your area';$('#canvasLeadTime').textContent=(control('leadTime')?.value||'').trim()||'Your lead time';const canvas=$('#studioCanvas');for(const style of ['minimal','editorial','catalog','services','portfolio'])canvas.classList.remove('style-'+style);canvas.classList.add('style-'+(selected('siteStyle')||'minimal'));const cards=$('#canvasOfferings');cards.replaceChildren();const items=$$('[data-offering]').map(offeringValues).filter((item)=>item.name.trim());for(const item of (items.length?items:[{name:'Your first offering',description:'Product or service details',price:'',currency:'INR'}]).slice(0,6)){const card=node('div','canvas-offering');card.append(node('strong','',item.name),node('span','',formatPrice(item)));cards.appendChild(card)}const claims=$('#canvasClaims');claims.replaceChildren();for(const claim of (control('suppliedClaims')?.value||'').split(/\\r?\\n/).map((value)=>value.trim()).filter(Boolean).slice(0,4))claims.appendChild(node('span','canvas-claim',claim));const media=$('#canvasMedia');media.replaceChildren();const imageIndex=mediaFiles.findIndex((file)=>file.type.startsWith('image/'));if(imageIndex>=0&&mediaObjectUrls[imageIndex]){const image=document.createElement('img');image.src=mediaObjectUrls[imageIndex];image.alt='Selected business preview';media.appendChild(image)}else media.appendChild(node('span','','YOUR PHOTO'))}
function renderMediaManager(){const list=$('#mediaList');list.replaceChildren();mediaObjectUrls.forEach((url)=>URL.revokeObjectURL(url));mediaObjectUrls=mediaFiles.map((file)=>URL.createObjectURL(file));const stored=storedIds('referenceAssetIds');for(const [index,file] of mediaFiles.entries()){const card=node('article','media-card');let visual;if(file.type.startsWith('image/')){visual=document.createElement('img');visual.src=mediaObjectUrls[index];visual.alt=''}else{visual=document.createElement('video');visual.src=mediaObjectUrls[index];visual.muted=true;visual.setAttribute('aria-label','Selected video')}const remove=node('button','','×');remove.type='button';remove.setAttribute('aria-label','Remove '+file.name);remove.addEventListener('click',()=>{takeSnapshot();mediaFiles.splice(index,1);syncFileInput();renderMediaManager();markDirty()});card.append(visual,node('span','',file.name),remove);list.appendChild(card)}if(stored.length){const saved=node('article','media-card saved-media');saved.append(node('span','',stored.length+' saved private '+(stored.length===1?'asset':'assets')));list.appendChild(saved)}if(!mediaFiles.length&&!stored.length)list.appendChild(node('p','fine','Your private media will appear here before upload.'));$('#mediaCount').textContent=(mediaFiles.length+stored.length)+' selected';renderCanvas()}
function syncFileInput(){if(typeof DataTransfer==='undefined')return;const transfer=new DataTransfer();mediaFiles.forEach((file)=>transfer.items.add(file));$('#references').files=transfer.files}

function hydrateProject(entry){const project=entry.project||{};setRadio('intent',project.intent);setRadio('siteStyle',project.siteStyle);setRadio('reelTemplate',project.reelTemplate);setField('businessName',project.businessName);setField('description',project.description);setField('orderWhatsAppNumber',project.orderWhatsAppNumber);setField('fulfillmentArea',project.fulfillmentArea);setField('leadTime',project.leadTime);setField('timezone',project.timezone||'Asia/Kolkata');setField('suppliedClaims',(project.suppliedClaims||[]).join('\\n'));hydrateOfferings(project.offerings);if(project.layerOverrides){setField('hook',project.layerOverrides.hook);setField('proof',project.layerOverrides.proof);setField('cta',project.layerOverrides.cta);setField('accent',project.layerOverrides.accent);setField('pacing',project.layerOverrides.pacing)}form.dataset.projectId=entry.projectId;form.dataset.revisionId=entry.revisionId;form.dataset.referenceAssetIds=JSON.stringify(project.referenceAssetIds||[]);form.dataset.siteAssetIds=JSON.stringify(project.siteAssetIds||[]);loadedProjectId=entry.projectId;loadedRevision=entry.revisionId;formDirty=false;history=[];$('#undoButton').disabled=true;setVersionCue('Saved revision '+String(entry.revisionId).slice(-8));setVisibility();renderMediaManager();$('#saveStatus').textContent='Loaded '+project.businessName+' from '+(entry.source==='whatsapp'?'WhatsApp':'Studio')+'.'}
function renderProjects(projects){const container=$('#savedProjects');container.replaceChildren();if(!projects.length){container.appendChild(node('p','fine','No saved work yet. Send a WhatsApp voice note or start below.'));return}for(const entry of projects){const button=node('button','secondary project-chip');button.type='button';const title=node('strong','',entry.project.businessName);const detail=node('small','',(entry.source==='whatsapp'?'From WhatsApp':'From Studio')+' · '+entry.intent);button.append(title,detail);button.addEventListener('click',()=>hydrateProject(entry));container.appendChild(button)}}
function cursorFor(projects){if(!projects.length)return undefined;const latest=[...projects].sort((a,b)=>a.createdAt-b.createdAt||String(a.projectId).localeCompare(String(b.projectId))||String(a.revisionId).localeCompare(String(b.revisionId))).at(-1);return latest.createdAt+':'+encodeURIComponent(latest.projectId)+':'+encodeURIComponent(latest.revisionId)}
function applyProjectChanges(changes){for(const change of changes){const index=projectCache.findIndex((entry)=>entry.projectId===change.projectId);if(index>=0)projectCache[index]=change;else projectCache.push(change)}projectCache.sort((a,b)=>b.createdAt-a.createdAt||String(b.revisionId).localeCompare(String(a.revisionId)));renderProjects(projectCache);const latest=projectCache[0];const loadedLatest=projectCache.find((entry)=>entry.projectId===loadedProjectId);if(latest&&!loadedProjectId&&!formDirty)hydrateProject(latest);else if(loadedLatest&&loadedLatest.revisionId!==loadedRevision&&!formDirty)hydrateProject(loadedLatest);else if(loadedLatest&&loadedLatest.revisionId!==loadedRevision&&formDirty)$('#syncStatus').lastChild.textContent=' New WhatsApp changes are ready in Saved work.';else $('#syncStatus').lastChild.textContent=' WhatsApp and Studio are synced.'}
function acceptAccount(data){sessionAuthenticated=true;$('#accountName').textContent=data.account.displayName;projectCache=data.projects||[];syncCursor=cursorFor(projectCache);applyProjectChanges([])}
async function refreshAccount(){const response=await api('/api/studio/me',{cache:'no-store'});if(!response.ok){if(sessionAuthenticated)$('#syncStatus').lastChild.textContent=' Your session ended. Sign in again to continue.';return}acceptAccount(await response.json())}
async function refreshChanges(){if(!sessionAuthenticated)return;const suffix=syncCursor?'?cursor='+encodeURIComponent(syncCursor):'';const response=await api('/api/studio/projects/changes'+suffix,{cache:'no-store'});if(!response.ok){if(response.status===401)$('#syncStatus').lastChild.textContent=' Your session ended. Sign in again to continue.';else $('#syncStatus').lastChild.textContent=' Sync is retrying; your edits are safe.';return}const data=await response.json();if(data.cursor)syncCursor=data.cursor;applyProjectChanges(data.changes||[])}

$$('input[name="intent"]').forEach((item)=>item.addEventListener('change',()=>{setVisibility();activateSection('basics')}));$$('[data-editor-target]').forEach((button)=>button.addEventListener('click',()=>activateSection(button.dataset.editorTarget)));Array.from(previewDevice.querySelectorAll('[data-device]')).forEach((button)=>button.addEventListener('click',()=>{Array.from(previewDevice.querySelectorAll('[data-device]')).forEach((item)=>item.classList.toggle('active',item===button));$('#studioCanvas').classList.toggle('device-mobile',button.dataset.device==='mobile');$('#studioCanvas').classList.toggle('device-desktop',button.dataset.device==='desktop')}));
$('#addOfferingButton').addEventListener('click',()=>{createOffering({},true);markDirty()});$('#undoButton').addEventListener('click',undoDraft);$('#reloadChangesButton').addEventListener('click',()=>resolveConflict(false));$('#reapplyChangesButton').addEventListener('click',()=>resolveConflict(true));form.addEventListener('focusin',(event)=>{if(event.target.matches('input,textarea,select')&&event.target.type!=='file')takeSnapshot()});form.addEventListener('input',(event)=>{if(event.target.id!=='references')markDirty()});form.addEventListener('change',(event)=>{if(event.target.id!=='references')markDirty()});form.addEventListener('invalid',(event)=>{const section=event.target.closest('[data-editor-section]');if(section)activateSection(section.dataset.editorSection)},true);$('#references').addEventListener('change',(event)=>{takeSnapshot();mediaFiles=Array.from(event.target.files||[]);renderMediaManager();markDirty()});hydrateOfferings([{}]);setVisibility();renderMediaManager();
$('#studioModeButton').addEventListener('click',()=>showOutcome('studio'));$('#bothModeButton').addEventListener('click',()=>showOutcome('both'));
api('/api/studio/me',{cache:'no-store'}).then(async(response)=>{if(response.ok){showWorkspace();acceptAccount(await response.json())}}).catch(()=>{});
$('#linkButton').addEventListener('click',async()=>{if(sessionAuthenticated){showWorkspace();refreshAccount();return}const response=await api('/api/studio/link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent:selected('intent')})});if(!response.ok){$('#linkButton').textContent=response.status===429?'Try again in a few minutes.':'Could not start sign-in. Try again.';return}const result=await response.json();$('#path').classList.add('hidden');$('#linkPanel').classList.remove('hidden');$('#whatsappLink').href=result.whatsappUrl;linkPoll=setInterval(checkLink,1800)});
async function checkLink(){const response=await api('/api/studio/link/status',{method:'POST',cache:'no-store'});if(response.status===202)return;if(!response.ok){clearInterval(linkPoll);$('#linkStatus').textContent='This link expired. Refresh to start again.';return}clearInterval(linkPoll);sessionAuthenticated=true;showWorkspace();refreshAccount()}
$('#logoutButton').addEventListener('click',async()=>{const response=await api('/api/studio/logout',{method:'POST'});if(response.ok)location.assign('/studio')});
function storedIds(name){try{const value=JSON.parse(form.dataset[name]||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function friendlyMissing(missing){const labels={orderWhatsAppNumber:'order WhatsApp number',fulfillmentArea:'area served',leadTime:'lead time',offerings:'at least one product or service',referenceAssetIds:'at least one real photo'};return missing.map((item)=>labels[item]||item).join(', ')}
function showApproval(result,kind){activeApproval=result.approval.approvalId;activeReel=kind==='reel'?result.reelId:undefined;$('#checklist').textContent=result.approval.checklist;$('#previewLink').classList.toggle('hidden',kind==='reel');$('#publishPanel').querySelector('h3').textContent=kind==='reel'?'Your reel plan is ready':'Your private preview passed its checks';$('#publishButton').textContent=kind==='reel'?'Approve private render':'Publish this version';$('#confirmPublish').parentElement.lastChild.textContent=kind==='reel'?' I reviewed this exact plan and approve one private render.':' I reviewed this exact preview and want it live.';$('#publishPanel').classList.remove('hidden');$('#publishPanel').scrollIntoView({behavior:'smooth'})}
form.addEventListener('submit',async(event)=>{event.preventDefault();const status=$('#saveStatus');const submit=form.querySelector('button[type="submit"]');submit.disabled=true;status.textContent='Saving your details and media securely…';$('#publishPanel').classList.add('hidden');const intent=selected('intent');const payload={intent,businessName:control('businessName').value,description:control('description').value,referenceAssetIds:storedIds('referenceAssetIds'),siteAssetIds:storedIds('siteAssetIds'),suppliedClaims:control('suppliedClaims').value.split(/\\r?\\n/).map((value)=>value.trim()).filter(Boolean)};if(form.dataset.projectId){payload.projectId=form.dataset.projectId;payload.parentRevisionId=form.dataset.revisionId}if(intent!=='reels'){payload.siteStyle=selected('siteStyle');payload.orderWhatsAppNumber=control('orderWhatsAppNumber').value;payload.fulfillmentArea=control('fulfillmentArea').value;payload.leadTime=control('leadTime').value;payload.timezone=control('timezone').value;payload.offerings=offerings()}if(intent!=='website'){payload.reelTemplate=selected('reelTemplate');payload.layerOverrides={hook:control('hook').value,proof:control('proof').value,cta:control('cta').value,accent:control('accent').value,pacing:control('pacing').value}}
let saved=await api('/api/studio/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(saved.status===409){showConflict(await saved.json().catch(()=>({})));status.textContent='A newer WhatsApp version arrived. Choose how to merge it above.';submit.disabled=false;return}if(!saved.ok){status.textContent='Check the business details and try again.';submit.disabled=false;return}let project=await saved.json();loadedProjectId=project.projectId;form.dataset.projectId=project.projectId;form.dataset.revisionId=project.revisionId;const files=[...mediaFiles];const assetIds=[...payload.referenceAssetIds];const siteAssetIds=[...payload.siteAssetIds];for(const file of files){const localId='reference-'+crypto.randomUUID();const upload=await api('/api/studio/assets/'+localId,{method:'PUT',headers:{'content-type':file.type,'x-axcas-project-id':project.projectId},body:file});if(!upload.ok){status.textContent='One file could not upload. Use JPG, PNG, WebP or MP4 under 16 MB.';submit.disabled=false;return}const uploaded=await upload.json();assetIds.push(uploaded.assetId);if(file.type.startsWith('image/'))siteAssetIds.push(uploaded.assetId)}
if(files.length){const revision={...payload,projectId:project.projectId,parentRevisionId:project.revisionId,referenceAssetIds:assetIds,siteAssetIds};saved=await api('/api/studio/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(revision)});if(saved.status===409){showConflict(await saved.json().catch(()=>({})));status.textContent='Your files are safe, but a newer WhatsApp version arrived. Choose how to merge it above.';submit.disabled=false;return}if(!saved.ok){status.textContent='Files uploaded, but the final draft could not be saved.';submit.disabled=false;return}project=await saved.json();form.dataset.revisionId=project.revisionId;form.dataset.referenceAssetIds=JSON.stringify(assetIds);form.dataset.siteAssetIds=JSON.stringify(siteAssetIds);mediaFiles=[];syncFileInput();renderMediaManager()}loadedRevision=project.revisionId;formDirty=false;history=[];$('#undoButton').disabled=true;setVersionCue('Saved revision '+String(project.revisionId).slice(-8));
if(intent==='reels'){status.textContent='Preparing your three angles and exact render checklist…';const response=await api('/api/studio/projects/'+project.projectId+'/reel',{method:'POST'});const result=await response.json().catch(()=>({}));if(!response.ok){status.textContent=result.stage==='needs_input'?'Add '+friendlyMissing(result.missing)+'.':'The reel plan needs a quick correction.';submit.disabled=false;return}status.textContent='Recommended angles: '+result.suggestions.join(' · ');showApproval(result,'reel');submit.disabled=false;refreshChanges();return}
status.textContent='Building and independently checking your private preview…';const response=await api('/api/studio/projects/'+project.projectId+'/build',{method:'POST'});const result=await response.json().catch(()=>({}));if(response.status===409&&result.stage==='needs_input'){status.textContent='One quick correction: add '+friendlyMissing(result.missing)+'.';submit.disabled=false;return}if(!response.ok&&response.status!==202){status.textContent='The preview did not pass its checks yet. Nothing was published.';submit.disabled=false;return}$('#previewLink').href=result.previewUrl;status.textContent=response.status===202?'Private preview ready; independent verification is queued.':'Private preview ready and checked.';if(result.stage==='approval_required')showApproval(result,'site');submit.disabled=false;refreshChanges()});
async function pollReel(reelId){const response=await api('/api/studio/reels/'+reelId,{cache:'no-store'});if(!response.ok){$('#publishStatus').textContent='Render status is temporarily unavailable.';return}const result=await response.json();if(result.status==='rendered'){const link=node('a','','Download your finished reel');link.href=result.mediaUrl;$('#publishStatus').textContent='Render complete. ';$('#publishStatus').appendChild(link);return}if(result.status==='failed'){$('#publishStatus').textContent='The render failed safely; no file was delivered.';return}$('#publishStatus').textContent='Rendering privately on Axcas…';setTimeout(()=>pollReel(reelId),4000)}
$('#publishButton').addEventListener('click',async()=>{const status=$('#publishStatus');if(!$('#confirmPublish').checked){status.textContent='Tick the review box before continuing.';return}if(!activeApproval)return;$('#publishButton').disabled=true;status.textContent=activeReel?'Starting one private render…':'Publishing this exact checked version…';const response=await api('/api/studio/approvals/'+activeApproval,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision:'approved'})});const result=await response.json().catch(()=>({}));if(!response.ok){status.textContent='Could not complete the approval. Refresh and try again.';$('#publishButton').disabled=false;return}if(result.stage==='rendering'&&result.reelId){pollReel(result.reelId);return}if(result.siteUrl){status.textContent='Live now: ';const link=node('a','',result.siteUrl);link.href=result.siteUrl;link.target='_blank';link.rel='noopener noreferrer';status.appendChild(link)}else status.textContent='Approved. Publication is finishing now.'});
})();`;
}
