function page(title: string, body: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>:root{color-scheme:light}body{margin:0;background:#fffaf5;color:#241b18;font:16px/1.65 system-ui,-apple-system,"Segoe UI",sans-serif}main{width:min(760px,calc(100% - 32px));margin:0 auto;padding:56px 0 80px}a{color:#176b49}h1{font-size:clamp(2.2rem,7vw,4.4rem);line-height:1;letter-spacing:-.055em;margin:12px 0 24px}h2{margin-top:34px}.brand{font-weight:850}.muted{color:#6d615d}.card{background:#fff;border:1px solid #eadfd6;border-radius:18px;padding:20px;margin:24px 0}li{margin:7px 0}</style></head><body><main><div class="brand">Axcas</div>${body}</main></body></html>`;
}

export function renderPrivacyPolicy(): string {
  return page("Axcas Privacy Policy", `<p class="muted">Effective 18 August 2026</p><h1>Axcas Privacy Policy</h1><p>Axcas helps small businesses create and improve a business page and original reel drafts through WhatsApp or a guided web studio, receive enquiries, and—only after separate consent and approval—qualify supplied leads.</p><h2>Information we process</h2><ul><li>WhatsApp sender identity, messages, voice-note transcription, provider message IDs, and approval decisions.</li><li>Short-lived browser-link records, hashed Studio session credentials, and append-only project revisions.</li><li>Business details, prices, service area, policies, photos, videos, reference media, and layer choices supplied by the merchant.</li><li>Random first-party session identifiers, page views, and WhatsApp CTA clicks. We hash the session identifier and do not store visitor IP addresses.</li><li>For an explicitly approved call: consent evidence, structured qualification outcome, cost, and a consented recording retained for no more than 30 days.</li></ul><h2>How we use it</h2><p>We use this information only to provide the requested Axcas service, secure tenant boundaries, verify releases, measure page activity, propose improvements, prevent abuse, and meet legal obligations. We do not sell personal information, scrape leads, take payments, or publish merchant content without the required approval.</p><h2>Service providers</h2><p>Processing may use Meta WhatsApp Business Cloud, Cloudflare, Convex, AWS, Hermes, and Vapi for an approved call. Each provider receives only the information needed for its role.</p><h2>Retention and security</h2><p>Business versions, Studio project revisions, approvals, security evidence, and metrics are retained as necessary to operate the service and preserve release integrity. Private media remains private unless the merchant selects it for publication. Studio sessions expire and may be revoked. Consented call recordings are deleted after 30 days; the structured outcome may remain. Secrets are not requested from customers.</p><h2>Your choices</h2><p>You may request access, correction, export, or deletion through the same Axcas WhatsApp control chat. Send <strong>DELETE MY DATA</strong> for deletion instructions. Revoking call consent or saying “do not call” stops future calls for that purpose.</p><div class="card"><strong>Contact</strong><p>Use the Axcas WhatsApp control conversation from which you received the service. Requests are identity-checked against that WhatsApp account.</p></div>`);
}

export function renderDataDeletion(): string {
  return page("Delete your Axcas data", `<p class="muted">Account and data deletion</p><h1>Delete your Axcas data</h1><p>You do not need a dashboard or developer account to request deletion.</p><div class="card"><ol><li>Open the Axcas WhatsApp control chat used for your business.</li><li>Send the exact phrase <strong>DELETE MY DATA</strong>.</li><li>Confirm the identity-bound deletion request when Axcas replies.</li></ol></div><p>After verification, Axcas will delete or de-identify the merchant profile, unpublished media, active site data, and associated personal information within 30 days. A minimal security or release record may be retained when required to prevent fraud, prove an approval, resolve disputes, or comply with law. Consented call recordings expire after 30 days regardless.</p><p>If you no longer have the original WhatsApp account, contact Axcas from the test or service conversation and provide the business name plus the prior order number. Additional verification will be required before deletion.</p><p><a href="/privacy">Read the Axcas Privacy Policy</a></p>`);
}

export function renderTermsOfService(): string {
  return page("Axcas Terms of Service", `<p class="muted">Effective 18 August 2026</p><h1>Axcas Terms of Service</h1><p>These terms apply when you use Axcas through WhatsApp, Axcas Studio, or an Axcas-hosted business page. By using the service, you confirm that you are authorized to act for the business and accept these terms.</p><h2>The service</h2><p>Axcas can prepare a structured business page, tracked WhatsApp enquiry links, private reel drafts, metrics, and verified improvement proposals. Studio provides guided layouts and layer controls; it is not a general-purpose code editor. Features may be released as a controlled beta. Axcas does not guarantee sales, reach, search ranking, or social engagement.</p><h2>Your content and responsibilities</h2><ul><li>You keep ownership of your business content and grant Axcas permission to process and publish only the assets and claims you approve.</li><li>You must supply accurate prices, availability, claims, order details, and content you have the right to use.</li><li>Reference media may guide pacing or layout, but you must not request copying another creator's footage, identity, voice, branding, or exact creative expression.</li><li>You must not use Axcas for unlawful, deceptive, infringing, abusive, or unsafe activity.</li><li>Leads must be supplied by the merchant with purpose-specific consent. Scraping, enrichment, and unapproved calls are prohibited.</li></ul><h2>Approvals</h2><p>Publishing a site, rendering a final reel, initiating a call batch, or changing an approved scope requires the applicable identity-bound approval. A redirect or click is not proof of an order, payment, fulfillment, or customer confirmation.</p><h2>Availability and providers</h2><p>The service relies on third-party providers including Meta, Cloudflare, Convex, AWS, Hermes, and Vapi. Maintenance, provider outages, policy changes, or account restrictions can affect availability. Axcas may suspend unsafe or non-compliant use.</p><h2>Charges</h2><p>Any subscription, included allowance, or usage charge is disclosed before purchase. Advertising spend, paid messaging, outbound calls, and other provider usage are outside the base service unless explicitly included.</p><h2>Ending use</h2><p>You may stop using Axcas or request deletion through the WhatsApp control chat. Axcas may end access for material breach, security risk, non-payment, or provider/legal requirements.</p><h2>Contact</h2><p>Use the same Axcas WhatsApp control conversation used for your business. See the <a href="/privacy">Privacy Policy</a> and <a href="/data-deletion">data deletion instructions</a>.</p>`);
}
